name: SZYDMCChatBridge
version: '1.1.4'
main: dev.szydmc.chatbridge.ChatBridgePlugin
api-version: '1.13'
description: Bukkit-compatible player chat bridge for the MC x QQ management platform.

softdepend: [AQQBot]
